version: "3.8"

services:
  frontend:
    image: ghcr.io/meyremmc/patient-point-client:latest
    ports:
      - "4200:80"
    restart: always

  core:
    image: ghcr.io/meyremmc/patient-point-server:latest
    ports:
      - "8080:8080"
    restart: always

  fhir:
    image: ghcr.io/meyremmc/patient-point-kis:latest
    ports:
      - "8081:8081"
    restart: always
